<?php
declare(strict_types=1);

return [
    'app_env' => 'production',
    'app_url' => 'https://game.brkovic.ltd',
    'session_cookie' => 'brk_game_session',
    'session_days' => 30,
    'login_code_ttl_minutes' => 10,
    'admin_emails' => [
        'vetus.nauta@gmail.com',
    ],
    'ecosystem_sso_enabled' => true,
    'ecosystem_sso_secret' => '2e91062b1d164d6cca08a0127d0c57ab2ac0287b7047f517b1d239c4d04cb80c',
    'brkovic_login_url' => 'https://brkovic.ltd/login',
    'atlas_secret_path' => '/home/brkovic/private/captain-ether-atlas.php',
    'atlas_mirror' => [
        'enabled' => false,
        'uri' => '',
        'uri_env' => 'CAPTAIN_ETHER_ATLAS_MIRROR_URI',
        'node_bin' => '/home/brkovic/nodevenv/journal-backend/24/bin/node',
        'driver_path' => '/home/brkovic/game.brkovic.ltd/private/node_modules/mongodb',
        'database' => 'captain_ether',
        'timeout_ms' => 15000,
        'error_log' => APP_ROOT . '/storage/atlas-mirror-error.log',
    ],
    'atlas_live_read' => [
        'enabled' => false,
        'answer_logs_enabled' => true,
        'progress_enabled' => true,
        'weak_points_enabled' => true,
        'watch_sessions_enabled' => true,
        'uri' => '',
        'uri_env' => 'CAPTAIN_ETHER_ATLAS_LIVE_READ_URI',
        'node_bin' => '/home/brkovic/nodevenv/journal-backend/24/bin/node',
        'driver_path' => '/home/brkovic/game.brkovic.ltd/private/node_modules/mongodb',
        'database' => 'captain_ether',
        'timeout_ms' => 15000,
        'error_log' => APP_ROOT . '/storage/atlas-live-read-error.log',
    ],
    'atlas_primary_write' => [
        'enabled' => false,
        'answer_logs_enabled' => true,
        'progress_enabled' => true,
        'weak_points_enabled' => true,
        'watch_sessions_enabled' => true,
        'json_shadow_enabled' => true,
        'uri' => '',
        'uri_env' => 'CAPTAIN_ETHER_ATLAS_PRIMARY_WRITE_URI',
        'node_bin' => '/home/brkovic/nodevenv/journal-backend/24/bin/node',
        'driver_path' => '/home/brkovic/game.brkovic.ltd/private/node_modules/mongodb',
        'database' => 'captain_ether',
        'timeout_ms' => 15000,
        'error_log' => APP_ROOT . '/storage/atlas-primary-write-error.log',
    ],
    'smtp_config_path' => '/home/brkovic/public_html/forms/config.php',
    'mail_from' => 'no-reply@brkovic.ltd',
    'mail_from_name' => 'Brkovic Maritime Games',
];
